#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/520823a6b4297616c5062f3c1965c16d
    # multi-region deployments, multi-cloud deployments, and droplets without
    # private networking need to use $public_ipv4
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001
  fleet:
    public-ip: $private_ipv4   # used for fleetctl ssh command
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
  users:
    - name: core
      passwd: abc123,,
      groups: 
        - sudo
        - docker
      ssh-authorized-key:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDskJaZiLdTgd2eqvi6Fs47WzVoBgpp4/pYRg0F8lIeAaW/Muffnvkwm1pVCp2rEqJnjV2Ob19HEgAUBlngT0OLWlPPVqXapz5AwSPh1AWyBSJi5xFvsCvQhKYVZz/q5vhgpOqFfvMAhdjPl8MtE3FVBlPlBVP9GLQi13L5H5Z03eYAvGjn9I5W1RzyZtzPhc/qWCuTW9AWyAIpns9GUvUQlcoqVVcIGeTg6b4j8UZYoAYJbVpB8vc3tkcYRpz9fCsq5g/FuHEZ8w2n0OQWU+e0/L9KgG3NCp7QsR8oz9rqjib2I6Mx/iegaQREnHKZaP6hnxb5mpZUNQJT51vutW5X asim@platalytics.com
        
